# Generated by Django 3.2.9 on 2021-11-15 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewflow', '0008_jsonfield_and_artifact'),
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.process')),
                ('leave_type', models.CharField(max_length=150)),
                ('leave_days', models.IntegerField()),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.process',),
        ),
        migrations.DeleteModel(
            name='HelloWorldProcess',
        ),
    ]
