# Generated by Django 3.2.9 on 2021-11-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0003_auto_20211115_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveprocess',
            name='employee_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
